# Mean

In [5]:
# Mean with a list not have outlayer data item
# use statastics module to find mean
import statistics
a=[1,2,3,4,5]

# here no outlayer data item
# a outlayer item is which data item have large differnce when compare with other elements 
mean=sum(a)/len(a)
print(mean)
print(statistics.mean(a))


3.0
3


In [4]:
# Mean with a list  have outlayer data item

a=[1,2,3,4,100]

# here 100 outlayer data item
# 100 has a large differnce when compare with other elements it was responsible for the mean increment of other elements 
mean=sum(a)/len(a)
print(mean)

22.0


In [39]:
# Mean with numpy.array  have outlayer data item
import numpy as np
a=np.array([1,2,3,4,100])

# here 100 outlayer data item
# 100 has a large differnce when compare with other elements it was responsible for the mean increment of other elements 
# mean=sum(a)/len(a)

mean=np.mean(a)
print(mean)

22.0


# Median

In [26]:
# median is the extention of mean which is covers the mean limitations
# 1. have sort the data
# 2. if n is even middle two terms avarage term is the median
# 3. if n is odd (n+1)/2 term in the list is the median 
# usre statistics module to find it
# Find median with list

a=[1,2,4,3,90,56]
a.sort()
n=len(a)
if(n%2 ==0):
    median=(a[n//2]+a[n//2-1])//2
else :
    median=a[(n-1)//2]
    
print(median)
print(statistics.median(a))
print(statistics.median_low(a))
print(statistics.median_high(a))
print(statistics.median_grouped(a))

3
3.5
3
4
3.5


In [37]:
# median is the extention of mean which is covers the mean limitations 

# 1. have sort the data
# 2. if n is even middle two terms avarage term is the median
# 3. if n is odd (n+1)/2 term in the list is the median 

# find median with an array

# in the median it overcome the outlayers problem it not responsible for mean increament of other elements

import numpy as np 
a=np.array([1,2,4,3,90,56])
a=np.sort(a)
m=np.median(a)
print(a,m)

[ 1  2  3  4 56 90] 3.5


# Variance

In [46]:
# variance is use full to know how our data spred from a mean point
# Variance with a list
x=[1,2,3,4,100]
m=sum(x)/len(x)
var=0
for i in x:
    var+=(i-m)**2
    
var=var/len(x)
print(var)

1522.0


In [41]:
# variance is use full to know how our data spred from a mean point
# Variance with numpy
x=np.array([1,2,3,4,100])
m=mean

print(np.var(x))

1522.0


# Standerd deviation

In [10]:
# it was simbolized with sigma
# the formula was sqrt of variace
# standder deviation with a List

import math
import statistics
x=[1,2,3,4,100]

m=sum(x)/len(x)
var=0
for i in x:
    var+=(i-m)**2
    
var=var/len(x)
std=math.sqrt(var)
print(std)
print(statistics.stdev(x))

39.01281840626232
43.617656975128774


In [23]:
# Stander deviation  was simbolized with sigma
# the formula was sqrt of variace
# standder deviation with numpy

import math
import numpy as np
import statistics

x=np.array([1,2,3,4,100])
stand=x.std()
print(stand)
print(x)
# in Numpy statistics.stdev(x) was not working sometimes


39.01281840626232
[  1   2   3   4 100]


# Mode

In [53]:
from collections import Counter

# mode is nothing but the higher occurance of data item in the list or array
# this is the function which runs in statastics module
data = [1, 2, 3, 4, 5, 3, 3]

counter = Counter(data)

mode = counter.most_common(1)[0][0]

print(mode)


3


In [55]:
 import statistics

data =np.array ([1, 2, 3, 4, 5, 3, 3])

mode = statistics.mode(data)

print(mode)

3


# Matrix multiplaication

In [80]:

matrix1 = [[1, 2], [3,4]]
matrix2 = [[1,2],[3,4]]



def matrix_multiplication(matrix1, matrix2):
    
    if len(matrix1[0]) != len(matrix2):
        raise ValueError("The number of columns in the first matrix must be equal to the number of rows in the second matrix.")

    result_matrix = [[0 for i in range(len(matrix2[0]))] for j in range(len(matrix1))]

    for i in range(len(matrix1)):
            for j in range(len(matrix2[0])):
                for k in range(len(matrix2)):
                    result_matrix[i][j] += matrix1[i][k] * matrix2[k][j]

    return result_matrix






result_matrix = matrix_multiplication(matrix1, matrix2)

print(result_matrix)





                



[[7, 10], [15, 22]]


In [89]:
# We can easily find this with numpy.matmul() 

import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])

print(np.matmul(a,b) ,"\n")
print(np.dot(a,b))




[[ 7 10]
 [15 22]] 

[[ 7 10]
 [15 22]]


In [90]:
# shape is nothing but order of a matrix


print(a.shape)

(2, 2)


In [93]:
import numpy as np

a=np.array([1,2,3,4,5])

print(np.std(a))

1.4142135623730951


In [1]:
import numpy as np

def binomial_probability(n, k, p):
  """Calculates the binomial probability.

  Args:
    n: The total number of trials.
    k: The number of successes.
    p: The probability of success on each trial.

  Returns:
    The probability of getting exactly k successes in n trials.
  """

  # Calculate the binomial coefficient.
  nCk = np.math.factorial(n) / (np.math.factorial(k) * np.math.factorial(n - k))

  # Calculate the probability of k successes.
  pk = p**k

  # Calculate the probability of n - k failures.
  q_n_k = (1 - p)**(n - k)

  # Return the binomial probability.
  return nCk * pk * q_n_k

# Load the dataset into a Python object
coin_flips = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

# Calculate the binomial probability
probability = binomial_probability(n=10, k=5, p=0.5)

# Print the probability
print(probability)

0.24609375


In [3]:
import numpy as np
from scipy.stats import binom

# Load the dataset into a Python object
coin_flips = np.array([1, 0, 1, 1, 0, 1, 0, 1, 1, 0])

# Calculate the probability of getting each of the possible outcomes
probability = binom.pmf(coin_flips.sum(), n=10, p=0.5)

# Print the probability
print(probability)

0.2050781249999999


# Simple linear Regression

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("employees.csv")
print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'employees.csv'